datasets:
  root: "~/storage_ds/BigEarthNet-S2"
  metadata_parquet: "/root/bigearthnet/BigEarthNet-Models/df_balanced/teste2.parquet"
  metadata_snow_cloud_parquet: "/root/storage_ds/metadata_snow_cloud.parquet"
  img_size: 120
  upsampling_method: "bicubic"
  resize: 224


model: 
  model_name: "resnet50"
  pretrained: False
  num_classes: 19
  select_bands: [1,2,3,4,5,6,7,11,12]  ##[3,2,1] #RGB
  sentinel2_bands: {
                      0:  'B01',
                      1:  'B02',
                      2:  'B03',
                      3:  'B04',
                      4:  'B05',
                      5:  'B06',
                      6:  'B07',
                      7:  'B08',
                      8:  'B8A',
                      9:  'B09',
                      10: 'B10',
                      11: 'B11',
                      12: 'B12'
                      }

training:
  positional_weight: True
  sensitivity: 0.55
  seed: 41
  learning_rate: 1e-3
  scheduler: True
  scheduler_type: ReduceLROnPlateau  
  factor: 0.5
  optim: AdamW
  weight_decay: 1e-3
  momentum: True
  momentum_val: 0.9
  batch_size: 32
  augmentation: False
  n_epoch: 50
  num_workers: 8
  save_strategy: f1_score
  save_metric: f1_score 
  save_mode: max
  slice_of_training: 1.0
  albumentation: False

WANDB:
  track: True
  project_name: YOO-BigEarthNet-S2-DL-models